// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: socmsg.proto

package com.bluedon.protobuf;

public final class LogMessage {
  private LogMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(LogMessage.registerSn);
  }
  public interface MessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Message> {
    
    // required uint64 serial_no = 1;
    boolean hasSerialNo();
    long getSerialNo();
    
    // optional uint32 version = 2 [default = 16777216];
    boolean hasVersion();
    int getVersion();
    
    // optional .Message.ServiceNo service_no = 3 [default = SESSION];
    boolean hasServiceNo();
    Message.ServiceNo getServiceNo();
    
    // required uint64 time = 4;
    boolean hasTime();
    long getTime();
    
    // optional .Message.Mode mode = 5 [default = REQUEST];
    boolean hasMode();
    Message.Mode getMode();
    
    // optional uint32 code = 6 [default = 0];
    boolean hasCode();
    int getCode();
    
    // optional string desc = 7;
    boolean hasDesc();
    String getDesc();
    
    // optional bytes content = 8;
    boolean hasContent();
    com.google.protobuf.ByteString getContent();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Message> implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogMessage.internal_static_Message_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogMessage.internal_static_Message_fieldAccessorTable;
    }
    
    public enum Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      REQUEST(0, 0),
      RESPONSE(1, 1),
      REQUESTS(2, 2),
      RESPONSES(3, 3),
      ;
      
      public static final int REQUEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      public static final int REQUESTS_VALUE = 2;
      public static final int RESPONSES_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Mode valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          case 2: return REQUESTS;
          case 3: return RESPONSES;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
              public Mode findValueByNumber(int number) {
                return Mode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Mode[] VALUES = {
        REQUEST, RESPONSE, REQUESTS, RESPONSES, 
      };
      
      public static Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Mode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Message.Mode)
    }
    
    public enum ServiceNo
        implements com.google.protobuf.ProtocolMessageEnum {
      REGISTER(0, 100000),
      SESSION(1, 100001),
      START_PLUGIN(2, 100002),
      STOP_PLUGIN(3, 100003),
      START_AGENT(4, 100004),
      STOP_AGENT(5, 100005),
      MONITOR_HOST(6, 100006),
      LOG(7, 200000),
      PERFORMANCE(8, 200001),
      SERVICE(9, 200002),
      SYSTEM(10, 999999),
      ;
      
      public static final int REGISTER_VALUE = 100000;
      public static final int SESSION_VALUE = 100001;
      public static final int START_PLUGIN_VALUE = 100002;
      public static final int STOP_PLUGIN_VALUE = 100003;
      public static final int START_AGENT_VALUE = 100004;
      public static final int STOP_AGENT_VALUE = 100005;
      public static final int MONITOR_HOST_VALUE = 100006;
      public static final int LOG_VALUE = 200000;
      public static final int PERFORMANCE_VALUE = 200001;
      public static final int SERVICE_VALUE = 200002;
      public static final int SYSTEM_VALUE = 999999;
      
      
      public final int getNumber() { return value; }
      
      public static ServiceNo valueOf(int value) {
        switch (value) {
          case 100000: return REGISTER;
          case 100001: return SESSION;
          case 100002: return START_PLUGIN;
          case 100003: return STOP_PLUGIN;
          case 100004: return START_AGENT;
          case 100005: return STOP_AGENT;
          case 100006: return MONITOR_HOST;
          case 200000: return LOG;
          case 200001: return PERFORMANCE;
          case 200002: return SERVICE;
          case 999999: return SYSTEM;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ServiceNo>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServiceNo>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServiceNo>() {
              public ServiceNo findValueByNumber(int number) {
                return ServiceNo.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final ServiceNo[] VALUES = {
        REGISTER, SESSION, START_PLUGIN, STOP_PLUGIN, START_AGENT, STOP_AGENT, MONITOR_HOST, LOG, PERFORMANCE, SERVICE, SYSTEM, 
      };
      
      public static ServiceNo valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ServiceNo(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Message.ServiceNo)
    }
    
    private int bitField0_;
    // required uint64 serial_no = 1;
    public static final int SERIAL_NO_FIELD_NUMBER = 1;
    private long serialNo_;
    public boolean hasSerialNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSerialNo() {
      return serialNo_;
    }
    
    // optional uint32 version = 2 [default = 16777216];
    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getVersion() {
      return version_;
    }
    
    // optional .Message.ServiceNo service_no = 3 [default = SESSION];
    public static final int SERVICE_NO_FIELD_NUMBER = 3;
    private ServiceNo serviceNo_;
    public boolean hasServiceNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public ServiceNo getServiceNo() {
      return serviceNo_;
    }
    
    // required uint64 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTime() {
      return time_;
    }
    
    // optional .Message.Mode mode = 5 [default = REQUEST];
    public static final int MODE_FIELD_NUMBER = 5;
    private Mode mode_;
    public boolean hasMode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public Mode getMode() {
      return mode_;
    }
    
    // optional uint32 code = 6 [default = 0];
    public static final int CODE_FIELD_NUMBER = 6;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCode() {
      return code_;
    }
    
    // optional string desc = 7;
    public static final int DESC_FIELD_NUMBER = 7;
    private Object desc_;
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          desc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes content = 8;
    public static final int CONTENT_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    
    private void initFields() {
      serialNo_ = 0L;
      version_ = 16777216;
      serviceNo_ = ServiceNo.SESSION;
      time_ = 0L;
      mode_ = Mode.REQUEST;
      code_ = 0;
      desc_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSerialNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, serialNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, serviceNo_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, code_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDescBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, content_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, serialNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, serviceNo_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, code_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDescBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, content_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        ExtendableBuilder<
          Message, Builder> implements MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogMessage.internal_static_Message_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogMessage.internal_static_Message_fieldAccessorTable;
      }
      
      // Construct using com.bluedon.protobuf.LogMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serialNo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 16777216;
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceNo_ = ServiceNo.SESSION;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        mode_ = Mode.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000010);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.getDescriptor();
      }
      
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }
      
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNo_ = serialNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceNo_ = serviceNo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasSerialNo()) {
          setSerialNo(other.getSerialNo());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasServiceNo()) {
          setServiceNo(other.getServiceNo());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSerialNo()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serialNo_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              ServiceNo value = ServiceNo.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                serviceNo_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readUInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              Mode value = Mode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                mode_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              code_ = input.readUInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              desc_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 serial_no = 1;
      private long serialNo_ ;
      public boolean hasSerialNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSerialNo() {
        return serialNo_;
      }
      public Builder setSerialNo(long value) {
        bitField0_ |= 0x00000001;
        serialNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearSerialNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNo_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 version = 2 [default = 16777216];
      private int version_ = 16777216;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 16777216;
        onChanged();
        return this;
      }
      
      // optional .Message.ServiceNo service_no = 3 [default = SESSION];
      private ServiceNo serviceNo_ = ServiceNo.SESSION;
      public boolean hasServiceNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public ServiceNo getServiceNo() {
        return serviceNo_;
      }
      public Builder setServiceNo(ServiceNo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        serviceNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceNo_ = ServiceNo.SESSION;
        onChanged();
        return this;
      }
      
      // required uint64 time = 4;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .Message.Mode mode = 5 [default = REQUEST];
      private Mode mode_ = Mode.REQUEST;
      public boolean hasMode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public Mode getMode() {
        return mode_;
      }
      public Builder setMode(Mode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        mode_ = value;
        onChanged();
        return this;
      }
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mode_ = Mode.REQUEST;
        onChanged();
        return this;
      }
      
      // optional uint32 code = 6 [default = 0];
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000020;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // optional string desc = 7;
      private Object desc_ = "";
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        desc_ = value;
        onChanged();
        return this;
      }
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000040);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      void setDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        desc_ = value;
        onChanged();
      }
      
      // optional bytes content = 8;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Message)
  }
  
  public static final int REGISTER_SN_FIELD_NUMBER = 9;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Message,
      Long> registerSn = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Long.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014socmsg.proto\"\336\003\n\007Message\022\021\n\tserial_no\030" +
      "\001 \002(\004\022\031\n\007version\030\002 \001(\r:\01016777216\022/\n\nserv" +
      "ice_no\030\003 \001(\0162\022.Message.ServiceNo:\007SESSIO" +
      "N\022\014\n\004time\030\004 \002(\004\022$\n\004mode\030\005 \001(\0162\r.Message." +
      "Mode:\007REQUEST\022\017\n\004code\030\006 \001(\r:\0010\022\014\n\004desc\030\007" +
      " \001(\t\022\017\n\007content\030\010 \001(\014\">\n\004Mode\022\013\n\007REQUEST" +
      "\020\000\022\014\n\010RESPONSE\020\001\022\014\n\010REQUESTS\020\002\022\r\n\tRESPON" +
      "SES\020\003\"\305\001\n\tServiceNo\022\016\n\010REGISTER\020\240\215\006\022\r\n\007S" +
      "ESSION\020\241\215\006\022\022\n\014START_PLUGIN\020\242\215\006\022\021\n\013STOP_P" +
      "LUGIN\020\243\215\006\022\021\n\013START_AGENT\020\244\215\006\022\020\n\nSTOP_AGE",
      "NT\020\245\215\006\022\022\n\014MONITOR_HOST\020\246\215\006\022\t\n\003LOG\020\300\232\014\022\021\n" +
      "\013PERFORMANCE\020\301\232\014\022\r\n\007SERVICE\020\302\232\014\022\014\n\006SYSTE" +
      "M\020\277\204=*\010\010\t\020\200\200\200\200\002:\035\n\013register_sn\022\010.Message" +
      "\030\t \001(\004B\"\n\024com.bluedon.protobufB\nLogMessa" +
      "ge"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_descriptor,
              new String[] { "SerialNo", "Version", "ServiceNo", "Time", "Mode", "Code", "Desc", "Content", },
              Message.class,
              Message.Builder.class);
          registerSn.internalInit(descriptor.getExtensions().get(0));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
